#############################################################################
# Makefile for building: cView
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  Cviewer/Cviewer.pro
# Template: app
# Command: /home/fgrando/apps/qt/5.4/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile Cviewer/Cviewer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -ICviewer -I. -I../../apps/qt/5.4/gcc_64/include -I../../apps/qt/5.4/gcc_64/include/QtWidgets -I../../apps/qt/5.4/gcc_64/include/QtGui -I../../apps/qt/5.4/gcc_64/include/QtCore -I. -I. -I../../apps/qt/5.4/gcc_64/mkspecs/linux-g++
QMAKE         = /home/fgrando/apps/qt/5.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cView1.0.0
DISTDIR = /home/fgrando/Downloads/cview/Cviewer/.tmp/cView1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/fgrando/apps/qt/5.4/gcc_64 -Wl,-rpath,/home/fgrando/apps/qt/5.4/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/fgrando/apps/qt/5.4/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Cviewer/main.cpp \
		Cviewer/mainwindow.cpp qrc_images.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrc_images.o \
		moc_mainwindow.o
DIST          = ../apps/qt/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../apps/qt/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../apps/qt/5.4/gcc_64/mkspecs/common/unix.conf \
		../apps/qt/5.4/gcc_64/mkspecs/common/linux.conf \
		../apps/qt/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../apps/qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../apps/qt/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../apps/qt/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../apps/qt/5.4/gcc_64/mkspecs/qconfig.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../apps/qt/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../apps/qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../apps/qt/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/default_pre.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/default_post.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/qt.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/resources.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/moc.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/uic.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/yacc.prf \
		../apps/qt/5.4/gcc_64/mkspecs/features/lex.prf \
		Cviewer/Cviewer/Cviewer.pro Cviewer/mainwindow.h Cviewer/main.cpp \
		Cviewer/mainwindow.cpp
QMAKE_TARGET  = cView
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = cView


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Cviewer/Cviewer.pro ../../apps/qt/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../../apps/qt/5.4/gcc_64/mkspecs/common/unix.conf \
		../../apps/qt/5.4/gcc_64/mkspecs/common/linux.conf \
		../../apps/qt/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../../apps/qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../apps/qt/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../../apps/qt/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../../apps/qt/5.4/gcc_64/mkspecs/qconfig.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../apps/qt/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/default_pre.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/default_post.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/qt.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/resources.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/moc.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/uic.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/yacc.prf \
		../../apps/qt/5.4/gcc_64/mkspecs/features/lex.prf \
		Cviewer/Cviewer.pro \
		Cviewer/images.qrc \
		/home/fgrando/apps/qt/5.4/gcc_64/lib/libQt5Widgets.prl \
		/home/fgrando/apps/qt/5.4/gcc_64/lib/libQt5Gui.prl \
		/home/fgrando/apps/qt/5.4/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile Cviewer/Cviewer.pro
../../apps/qt/5.4/gcc_64/mkspecs/features/spec_pre.prf:
../../apps/qt/5.4/gcc_64/mkspecs/common/shell-unix.conf:
../../apps/qt/5.4/gcc_64/mkspecs/common/unix.conf:
../../apps/qt/5.4/gcc_64/mkspecs/common/linux.conf:
../../apps/qt/5.4/gcc_64/mkspecs/common/gcc-base.conf:
../../apps/qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../apps/qt/5.4/gcc_64/mkspecs/common/g++-base.conf:
../../apps/qt/5.4/gcc_64/mkspecs/common/g++-unix.conf:
../../apps/qt/5.4/gcc_64/mkspecs/qconfig.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../apps/qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../apps/qt/5.4/gcc_64/mkspecs/features/qt_functions.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/qt_config.prf:
../../apps/qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf:
../../apps/qt/5.4/gcc_64/mkspecs/features/spec_post.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/default_pre.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/resolve_config.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/default_post.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/warn_on.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/qt.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/resources.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/moc.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/unix/opengl.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/uic.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/unix/thread.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/exceptions.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/yacc.prf:
../../apps/qt/5.4/gcc_64/mkspecs/features/lex.prf:
Cviewer/Cviewer.pro:
Cviewer/images.qrc:
/home/fgrando/apps/qt/5.4/gcc_64/lib/libQt5Widgets.prl:
/home/fgrando/apps/qt/5.4/gcc_64/lib/libQt5Gui.prl:
/home/fgrando/apps/qt/5.4/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile Cviewer/Cviewer.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Cviewer/images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents Cviewer/mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents Cviewer/main.cpp Cviewer/mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Cviewer/mainwindow.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: Cviewer/images.qrc \
		Cviewer/images/folder-2x.png \
		Cviewer/images/project-2x.png \
		Cviewer/images/magnifying-glass-2x.png \
		Cviewer/images/sort-ascending-2x.png \
		Cviewer/images/layers-2x.png \
		Cviewer/images/puzzle-piece-2x.png \
		Cviewer/images/eye-2x.png \
		Cviewer/images/share-boxed-2x.png \
		Cviewer/images/wrench-2x.png \
		Cviewer/images/cog-2x.png \
		Cviewer/images/loop-circular-2x.png \
		Cviewer/images/fork-8x.png \
		Cviewer/images/play-circle-2x.png \
		Cviewer/images/reload-2x.png
	/home/fgrando/apps/qt/5.4/gcc_64/bin/rcc -name images Cviewer/images.qrc -o qrc_images.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../apps/qt/5.4/gcc_64/include/QtWidgets/QMainWindow \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qmainwindow.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qwidget.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qglobal.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qconfig.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qlogging.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qflags.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qmutex.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qobject.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qstring.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qchar.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qlist.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qiterator.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qisenum.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qmargins.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qrect.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsize.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qpoint.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpalette.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qcolor.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qrgb.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qpair.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qregexp.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qbrush.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qvector.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qmatrix.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpolygon.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qregion.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qline.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qtransform.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpainterpath.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qimage.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpixelformat.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpixmap.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qhash.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qfont.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qfontinfo.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qcursor.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qkeysequence.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qevent.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qvariant.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qmap.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qdebug.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qlocale.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qset.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qurl.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qurlquery.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qfile.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qfiledevice.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qvector2d.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qtabwidget.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qicon.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/QString \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QFileSystemModel \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qfilesystemmodel.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qdir.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qfileinfo.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qdiriterator.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/QModelIndex \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QListWidgetItem \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qlistwidget.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qlistview.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qframe.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qstyleoption.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qvalidator.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qregularexpression.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qslider.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractslider.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qstyle.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qtabbar.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qrubberband.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/QStringList \
		../../apps/qt/5.4/gcc_64/include/QtCore/QProcess \
		../../apps/qt/5.4/gcc_64/include/QtCore/qprocess.h \
		Cviewer/mainwindow.h
	/home/fgrando/apps/qt/5.4/gcc_64/bin/moc $(DEFINES) -I/home/fgrando/apps/qt/5.4/gcc_64/mkspecs/linux-g++ -I/home/fgrando/Downloads/cview/Cviewer -I/home/fgrando/apps/qt/5.4/gcc_64/include -I/home/fgrando/apps/qt/5.4/gcc_64/include/QtWidgets -I/home/fgrando/apps/qt/5.4/gcc_64/include/QtGui -I/home/fgrando/apps/qt/5.4/gcc_64/include/QtCore -I. Cviewer/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: Cviewer/mainwindow.ui
	/home/fgrando/apps/qt/5.4/gcc_64/bin/uic Cviewer/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: Cviewer/main.cpp Cviewer/mainwindow.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QMainWindow \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qmainwindow.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qwidget.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qglobal.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qconfig.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qlogging.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qflags.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qmutex.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qobject.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qstring.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qchar.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qlist.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qiterator.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qisenum.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qmargins.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qrect.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsize.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qpoint.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpalette.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qcolor.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qrgb.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qpair.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qregexp.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qbrush.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qvector.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qmatrix.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpolygon.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qregion.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qline.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qtransform.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpainterpath.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qimage.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpixelformat.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpixmap.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qhash.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qfont.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qfontinfo.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qcursor.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qkeysequence.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qevent.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qvariant.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qmap.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qdebug.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qlocale.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qset.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qurl.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qurlquery.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qfile.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qfiledevice.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qvector2d.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qtabwidget.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qicon.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/QString \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QFileSystemModel \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qfilesystemmodel.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qdir.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qfileinfo.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qdiriterator.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/QModelIndex \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QListWidgetItem \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qlistwidget.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qlistview.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qframe.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qstyleoption.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qvalidator.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qregularexpression.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qslider.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractslider.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qstyle.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qtabbar.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qrubberband.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/QStringList \
		../../apps/qt/5.4/gcc_64/include/QtCore/QProcess \
		../../apps/qt/5.4/gcc_64/include/QtCore/qprocess.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QApplication \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qapplication.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qeventloop.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qguiapplication.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Cviewer/main.cpp

mainwindow.o: Cviewer/mainwindow.cpp Cviewer/mainwindow.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QMainWindow \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qmainwindow.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qwidget.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qglobal.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qconfig.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qfeatures.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qtypetraits.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsysinfo.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qlogging.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qflags.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qmutex.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qnumeric.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qnamespace.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qobject.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qstring.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qchar.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qbytearray.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qrefcount.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qarraydata.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qlist.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qalgorithms.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qiterator.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcoreevent.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qmetatype.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qisenum.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qobject_impl.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qmargins.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qrect.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsize.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qpoint.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpalette.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qcolor.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qrgb.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qstringlist.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qdatastream.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qiodevice.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qpair.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qregexp.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qbrush.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qvector.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qmatrix.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpolygon.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qregion.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qline.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qtransform.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpainterpath.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qimage.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpixelformat.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpixmap.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qshareddata.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qhash.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qfont.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qfontinfo.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qcursor.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qkeysequence.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qevent.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qvariant.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qmap.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qdebug.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qtextstream.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qlocale.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qset.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qurl.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qurlquery.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qfile.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qfiledevice.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qvector2d.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qtabwidget.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qicon.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/QString \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QFileSystemModel \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qfilesystemmodel.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qdir.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qfileinfo.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qdiriterator.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/QModelIndex \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QListWidgetItem \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qlistwidget.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qlistview.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qframe.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qstyleoption.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qvalidator.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qregularexpression.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qslider.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractslider.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qstyle.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qtabbar.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qrubberband.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/QStringList \
		../../apps/qt/5.4/gcc_64/include/QtCore/QProcess \
		../../apps/qt/5.4/gcc_64/include/QtCore/qprocess.h \
		ui_mainwindow.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/QVariant \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QAction \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qaction.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qactiongroup.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QApplication \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qapplication.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/qeventloop.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qguiapplication.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qinputmethod.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QButtonGroup \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qbuttongroup.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QCheckBox \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qcheckbox.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QFrame \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QGridLayout \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qgridlayout.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qlayout.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qboxlayout.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QHBoxLayout \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QHeaderView \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qheaderview.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QLabel \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qlabel.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QLineEdit \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qlineedit.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qtextcursor.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qtextformat.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qpen.h \
		../../apps/qt/5.4/gcc_64/include/QtGui/qtextoption.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QListWidget \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QMenuBar \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qmenubar.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qmenu.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QPushButton \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qpushbutton.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QStatusBar \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qstatusbar.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QToolBar \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qtoolbar.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QTreeView \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qtreeview.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QWidget \
		../../apps/qt/5.4/gcc_64/include/QtCore/QDebug \
		../../apps/qt/5.4/gcc_64/include/QtCore/QFileInfo \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/QMessageBox \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qmessagebox.h \
		../../apps/qt/5.4/gcc_64/include/QtWidgets/qdialog.h \
		../../apps/qt/5.4/gcc_64/include/QtCore/QRegExp \
		../../apps/qt/5.4/gcc_64/include/QtCore/QCoreApplication
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o Cviewer/mainwindow.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

